# Generated by Django 4.1.1 on 2022-09-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=40)),
                ("account_number", models.CharField(max_length=45, unique=True)),
                (
                    "total_assessts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
            options={
                "db_table": "accounts",
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("isin", models.CharField(max_length=70, unique=True)),
                ("asset_group", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "holdings",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.holding"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_holdings",
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=40)),
                (
                    "principal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.account"
                    ),
                ),
            ],
            options={
                "db_table": "investment",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apis.user"
            ),
        ),
    ]
