# Generated by Django 4.1.1 on 2022-09-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_transferidentifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferidentifier",
            name="status",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
