# Generated by Django 4.1.1 on 2022-09-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_transferidentifier_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferidentifier",
            name="signature",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
