# Generated by Django 4.1.1 on 2022-09-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0004_transferidentifier_signature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferidentifier",
            name="signature",
        ),
    ]
