# Generated by Django 4.1.1 on 2022-09-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('isin', models.CharField(max_length=70)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('asset_group', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'holdings',
            },
        ),
        migrations.CreateModel(
            name='UserHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdings.holding')),
            ],
            options={
                'db_table': 'user_holdings',
            },
        ),
    ]
