# Generated by Django 4.1.1 on 2022-09-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'investment',
            },
        ),
    ]
